spring:
  application:
    name: wso2-notifier-v2

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 7b38f9569af298
    password: 498d24cefc3958
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5433/wso2_notifier
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

elasticsearch:
  host: localhost
  port: 9200
  scheme: https
  username: elastic
  password: 4TN-fBGiqwZL75+aiivG
  ca-cert-path: /Users/chaari/Downloads/elasticsearch-9.3.0/config/certs/http_ca.crt

# Poll intervals for schedulers
usecases:
  delete:
    poll-interval-ms: 30000
  threshold:
    poll-interval-ms: 30000
  high-latency:
    poll-interval-ms: 30000
  faulty:
    poll-interval-ms: 30000
  brute-force:
    poll-interval-ms: 30000
  custom:
    poll-interval-ms: 30000

