-- Seed for all 5 initial notification rules
-- NOTE: Each statement must be on a SINGLE LINE because some Hibernate/JPA script executors do not support multi-line statements.

INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('BRUTE_FORCE_LOGIN', true, 'HIGH', 1, 300, '*', null, 'Alert when an IP fails login 3 times in 5 minutes across any portal.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('FAULTY', true, 'MEDIUM', 5, 60, '*', '900800,900801,900802,900803,900804', 'Alert when an API returns 5+ faulty events within 1 minute.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('HIGH_LATENCY', true, 'MEDIUM', 2000, 60, '*', null, 'Alert when API response latency exceeds 2000ms.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('THRESHOLD', false, 'LOW', 1000, 60, '*', null, 'Basic call volume threshold alert.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('DELETE_EVENT', true, 'CRITICAL', 1, 3600, '*', null, 'Instant alert on any API or Application deletion.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
INSERT INTO notification_rule (use_case_type, enabled, severity, threshold_value, lookback_seconds, api_names, error_codes, description, created_at, updated_at) VALUES ('PENDING_WORKFLOWS', true, 'MEDIUM', 1, 3600, '*', null, 'Alert when new pending workflows are detected in WSO2.', NOW(), NOW()) ON CONFLICT (use_case_type) DO NOTHING;
